export const VIEW_POST = 'post/VIEW_POST';
export const CREATE_POST = 'post/CREATE_POST';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
